# Generated by Django 6.0.3 on 2026-03-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0003_growthanalysis_portfoliorating'),
        ('stocks', '0006_stockuniverse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldSilverCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1mo', '1 Month'), ('3mo', '3 Months'), ('6mo', '6 Months'), ('1y', '1 Year'), ('2y', '2 Years'), ('5y', '5 Years')], default='5y', max_length=16)),
                ('interval', models.CharField(choices=[('1d', 'Daily'), ('1wk', 'Weekly'), ('1mo', 'Monthly')], default='1d', max_length=16)),
                ('correlation', models.FloatField(help_text='Correlation coefficient between gold and silver')),
                ('gold_data', models.JSONField(help_text='Historical GOLD price data')),
                ('silver_data', models.JSONField(help_text='Historical SILVER price data')),
                ('statistics', models.JSONField(help_text='Mean, std dev, trend analysis for both metals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gold Silver Correlation',
                'verbose_name_plural': 'Gold Silver Correlation Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['period', 'interval', '-created_at'], name='ml_analytic_period_e87d68_idx')],
            },
        ),
        migrations.CreateModel(
            name='NiftyClustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1mo', '1 Month'), ('3mo', '3 Months'), ('6mo', '6 Months'), ('1y', '1 Year'), ('2y', '2 Years'), ('5y', '5 Years')], default='1y', max_length=16)),
                ('interval', models.CharField(choices=[('1d', 'Daily'), ('1wk', 'Weekly'), ('1mo', 'Monthly')], default='1d', max_length=16)),
                ('n_clusters', models.PositiveSmallIntegerField(default=3)),
                ('clustering_data', models.JSONField(help_text='All NIFTY 50 stocks with cluster assignments')),
                ('summary', models.JSONField(help_text='Cluster summaries with statistics')),
                ('pca_explained_variance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NIFTY 50 Clustering',
                'verbose_name_plural': 'NIFTY 50 Clustering Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['period', 'interval', '-created_at'], name='ml_analytic_period_083cb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinearRegressionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField()),
                ('slope', models.FloatField()),
                ('intercept', models.FloatField()),
                ('latest_close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('predicted_next_close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('predicted_change_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data_source', models.CharField(default='yfinance', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_linear_regression_results', to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_linear_regression_results', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'Linear Regression Result',
                'verbose_name_plural': 'Linear Regression Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='ml_analytic_portfol_399ed0_idx'), models.Index(fields=['stock', '-created_at'], name='ml_analytic_stock_i_ac00f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogisticRegressionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField()),
                ('positive_days', models.PositiveIntegerField()),
                ('test_accuracy', models.FloatField()),
                ('probability_up_next_close', models.FloatField()),
                ('signal', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], max_length=32)),
                ('data_source', models.CharField(default='yfinance', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_logistic_regression_results', to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_logistic_regression_results', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'Logistic Regression Result',
                'verbose_name_plural': 'Logistic Regression Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='ml_analytic_portfol_d99f44_idx'), models.Index(fields=['stock', '-created_at'], name='ml_analytic_stock_i_9d495f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioClusteringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_clusters', models.PositiveSmallIntegerField(default=3)),
                ('clustering_data', models.JSONField(help_text='Raw clustering data with cluster assignments and PCA coordinates for each stock')),
                ('summary', models.JSONField(help_text='Summary statistics for each cluster (count, avg returns, avg volatility, etc.)')),
                ('pca_explained_variance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_clustering_results', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Clustering Result',
                'verbose_name_plural': 'Portfolio Clustering Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='ml_analytic_portfol_32711f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Why this stock is recommended', max_length=255)),
                ('recommendations', models.JSONField(help_text='List of recommended stocks with symbol, name, sector, price, PE ratio, market cap')),
                ('portfolio_sectors', models.JSONField(help_text='List of sectors currently in portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_recommendations', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Recommendation',
                'verbose_name_plural': 'Portfolio Recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='ml_analytic_portfol_4e1969_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(help_text='Markdown formatted text narrative')),
                ('groups', models.JSONField(help_text='Risk category groupings: High-Risk, Medium-Risk, Low-Risk stocks')),
                ('positive_count', models.IntegerField()),
                ('negative_count', models.IntegerField()),
                ('best_stock', models.CharField(blank=True, max_length=32)),
                ('worst_stock', models.CharField(blank=True, max_length=32)),
                ('best_return_percent', models.FloatField(blank=True, null=True)),
                ('worst_return_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_summary_reports', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Summary Report',
                'verbose_name_plural': 'Portfolio Summary Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='ml_analytic_portfol_249312_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockSentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral')], max_length=16)),
                ('positive_count', models.PositiveIntegerField()),
                ('negative_count', models.PositiveIntegerField()),
                ('neutral_count', models.PositiveIntegerField()),
                ('sentiment_score', models.FloatField(help_text='Aggregate sentiment score (positive - negative)')),
                ('news_breakdown', models.JSONField(help_text='Detailed sentiment per news item with title, sentiment, strength')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_sentiment_analyses', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'Stock Sentiment Analysis',
                'verbose_name_plural': 'Stock Sentiment Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', '-created_at'], name='ml_analytic_stock_i_c37de1_idx'), models.Index(fields=['overall_sentiment'], name='ml_analytic_overall_0e6d3c_idx')],
            },
        ),
    ]
